import Augmentor
# p = Augmentor.Pipeline("img")
p = Augmentor.Pipeline("img_raw", output_directory="../img")
# p.ground_truth("org_img")
p.rotate(probability=1, max_left_rotation=5, max_right_rotation=5)
p.flip_left_right(probability=0.5)
p.zoom_random(probability=0.5, percentage_area=0.8)
p.flip_top_bottom(probability=0.5)
p.random_distortion(probability=1, grid_width=4, grid_height=4, magnitude=8)
p.resize(probability=1.0, width=448, height=448)
p.sample(2000)
